
set BUILT_VERSION="2.0.0"
set MOD_NAME="SynthRidersWebsockets"

set RELEASE_BUILD_DIR=".\src\bin\Release\net6.0"
set MAIN_DLL="%RELEASE_BUILD_DIR%\%MOD_NAME%.dll"
set WEBSOCKET_DLL="%RELEASE_BUILD_DIR%\WebSocketDotNet.dll"
set SIGNAL_R_DLLS="%RELEASE_BUILD_DIR%\Microsoft.AspNetCore.*.dll"
REM set LIB_DLL_DIR="%RELEASE_BUILD_DIR%\libs"

set OUTPUT_DIR=".\build\%MOD_NAME%_v%BUILT_VERSION%"
mkdir %OUTPUT_DIR%

copy %MAIN_DLL% %OUTPUT_DIR%
copy %WEBSOCKET_DLL% %OUTPUT_DIR%
copy %SIGNAL_R_DLLS% %OUTPUT_DIR%
REM copy %LIB_DLL_DIR%\* %OUTPUT_DIR%
